{"uuid":"0a9d8408-e97c-4d06-a919-1b0702f7eae2","historyId":"b1c9b2bf6eac7e8e4ce2946f0bef2535","fullName":"com.thetestingacademy.base.BaseTest.setConfig","labels":[{"name":"package","value":"com.thetestingacademy.crud.INT.TC_Integration"},{"name":"testClass","value":"com.thetestingacademy.crud.INT.TC_Integration"},{"name":"testMethod","value":"setConfig"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"APIAutomationATB4X"},{"name":"subSuite","value":"com.thetestingacademy.crud.INT.TC_Integration"},{"name":"host","value":"MBP-C02DRR20MD6M"},{"name":"thread","value":"17326@MBP-C02DRR20MD6M.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"}],"links":[],"name":"setConfig","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.ExceptionInInitializerError","trace":"java.lang.ExceptionInInitializerError\n\tat com.thetestingacademy.base.BaseTest.setConfig(BaseTest.java:43)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)\n\tat org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\n\tat org.testng.TestRunner.run(TestRunner.java:621)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\n\tat org.testng.TestNG.run(TestNG.java:1082)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: java.lang.RuntimeException: com.codoid.products.exception.FilloException: No records found\n\tat com.thetestingacademy.endpoints.APIConstants.<clinit>(APIConstants.java:15)\n\t... 30 more\nCaused by: com.codoid.products.exception.FilloException: No records found\n\tat com.codoid.products.fillo.Recordset.<init>(Recordset.java:40)\n\tat com.codoid.products.fillo.Connection.executeQuery(Connection.java:69)\n\tat com.thetestingacademy.utils.FillowUtil.fetchDataFromXLSX(FillowUtil.java:18)\n\tat com.thetestingacademy.endpoints.APIConstants.<clinit>(APIConstants.java:13)\n\t... 30 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1698562628057,"stop":1698562628060}